# Generated by Django 2.2.12 on 2021-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210822_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام عکس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(upload_to='public/img/companies', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=False, to='product.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=250, null=True, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order_by_fname',
            field=models.CharField(max_length=250, verbose_name='سفارش با نام'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order_by_lname',
            field=models.CharField(max_length=250, verbose_name='سفارش با نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order_by_tel',
            field=models.CharField(max_length=250, verbose_name='سفارش با تلفن'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, 'پروژه تعریف شد'), (1, 'پروژه تایید شد'), (2, 'در حال ساخت پروژه'), (3, 'اتمام پروژه'), (4, 'پروژه تایید نشد')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], default=1, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.CharField(max_length=250, verbose_name='وب سایت'),
        ),
    ]
