# Generated by Django 2.2.12 on 2021-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='public/img/services')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
