# Generated by Django 2.2.12 on 2021-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='phone_number',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
